[package]
name = "dimpact"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
is-terminal = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
thiserror = "1.0"
anyhow = "1.0"
regex = "1.10"
walkdir = "2.5"

[dev-dependencies]
pretty_assertions = "1.4"
assert_cmd = "2.0"
predicates = "3.1"
tempfile = "3.10"
