name: Impact Analysis

on:
  pull_request:

jobs:
  impact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - id: impact
        name: Run impact & format tables
        run: |
          git fetch origin ${{ github.base_ref }} && \
          git diff --no-ext-diff origin/${{ github.base_ref }}...HEAD | \
          docker run -i --rm -v ${{ github.workspace }}:/work ghcr.io/n01e0/dimpact:latest impact --direction caller --with-pdg --with-edges -f json | \
          jq -r ' 
            "| Changed | Kind | Location |",
            "| ------- | ---- | -------- |",
            (.changed_symbols[]
              | "| \(.name) | \(.kind|ascii_upcase) | \(.file):\(.range.start_line) |"),
          
            "",
            "| Impacted | Kind | Location |",
            "| -------- | ---- | -------- |",
            (.impacted_symbols[]
              | "| \(.name) | \(.kind|ascii_upcase) | \(.file):\(.range.start_line) |")
          '  > impact-tables.md

      - name: comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: impact-tables.md
