name: Impact Analysis

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  impact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - id: impact
        name: Run impact & format tables
        run: |
          git fetch origin ${{ github.base_ref }} && \
          git diff --no-ext-diff origin/${{ github.base_ref }}...HEAD | \
          docker run -i --rm -v ${{ github.workspace }}:/work ghcr.io/n01e0/dimpact:latest impact --per-seed -f json | \
          jq -r '
          "## Changed Symbols\n",
          "| Name | Kind | File | Range |",
          "|------|------|------|-------|",
          (.[] | .changed_symbol as $c |
            "| [" + $c.name + "](#"+($c.name|ascii_downcase)+") | " +
            $c.kind + " | " +
            $c.file + " | " +
            ($c.range.start_line|tostring)+"-"+($c.range.end_line|tostring) + " |"
          ),
          "\n## Details\n",
          "<details><summary>Show details</summary>",
          (.[] | .changed_symbol as $c |
            "### <a name=\"" + ($c.name|ascii_downcase) + "\"></a>" + $c.name + "\n" +
            "<details><summary>Show details</summary>\n\n" +
            "- **ID:** `" + $c.id + "`\n" +
            "- **Kind:** `" + $c.kind + "`\n" +
            "- **File:** `" + $c.file + "`\n" +
            "- **Range:** `" + ($c.range.start_line|tostring) + "-" + ($c.range.end_line|tostring) + "`\n" +
            "- **Language:** `" + $c.language + "`\n\n" +
            "#### Impacts\n" +
            (if (.impacts | length) > 0 then
               (.impacts[] | "- Direction: " + .direction + "\n" +
                 "  - Impacted Symbols: " + ((.output.impacted_symbols[]?.name) | tostring)? + "\n" +
                 "  - Impacted Files: " + ((.output.impacted_files[])? // "None")
               )
             else "- None" end) + "\n\n</details>\n"
          ),
          "</details>"' > impact-tables.md

      - name: comment
        if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: impact-tables.md
